### ISSUE TITLE
Add messaging API to api module

### ISSUE THREAD

**Issue by karianna** [microsoft/gctoolkit#237] opened 2022-10-28 17:47 UTC
Current implementation has a circular dependency because we are too tightly coupled to vert.x.  Adding this API will break the code coupling which can lead to a further refactoring.

This is important before we add new features like GenShen and GenZGC parsing.

https://github.com/microsoft/gctoolkit/issues/237#tasklist-block-37859257-88f0-46f4-9886-0fc62a30d37e

**Comment by karianna** [comment] 2022-11-28 18:08
Messaging API has been settled upon. Parser and Analytics need to be rewired in and then the tests updated.

**Comment by dsgrieve** [comment] 2023-01-18 15:06
Duplicate of issue #4

**Comment by karianna** [comment] 2023-01-18 20:03
#252

**Closed** 2023-01-23 18:37 UTC
Labels: enhancement
